# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
jobs:
  test_unit_r:
    docker:
      - image: rocker/tidyverse:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run_r_cmd_build
          command: "R CMD build ."
      - run:
          name: run_r_cmd_check
          command: |
            RPKGNAME=`cat DESCRIPTION | egrep ^Package: | head -1 | awk '{print $2}'`
            RPKGVERSION=`cat DESCRIPTION | egrep ^Version: | head -1 | awk '{print $2}'`
            R CMD check --no-manual ${RPKGNAME}_${RPKGVERSION}.tar.gz
workflows:
  version: 2
  my_workflows:
    jobs:
      - test_unit_r
