# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
jobs:
  test_unit_r:
    docker:
      - image: rocker/tidyverse:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        command : "R CMD check ."
workflows:
  version: 2
  my_workflows:
    jobs:
      - test_unit_r
